{{ config(materialized='table') }}
with last_movies as (
select 
    dbt_scd_id as dim_movie_id,
    tmdb_id,
    imdb_id,
    status,
    original_title,
    release_date,
    budget,
    revenue,
    runtime,
    popularity,
    vote_average,
    vote_count,
    original_language,
    genres,
    production_companies,
    production_countries,
    spoken_languages,
    origin_country,
    credits,
    overview,
    poster_path,
    tagline,
    title,
    video,
    belongs_to_collection__id,
    belongs_to_collection__name,
    belongs_to_collection__poster_path,
    belongs_to_collection__backdrop_path,
    adult,
    backdrop_path,
    load_id,
    load_date,
    dlt_id, 
    dbt_valid_from,
    dbt_valid_to,
    ROW_NUMBER() OVER(PARTITION BY tmdb_id ORDER BY dbt_updated_at DESC) as rn
from {{ref('int_last_movie_changes_snapshot')}}
)
select 
    dim_movie_id,
    tmdb_id,
    imdb_id,
    status,
    original_title,
    release_date,
    runtime,
    original_language,
    genres,
    production_companies,
    production_countries,
    spoken_languages,
    origin_country,
    credits,
    overview,
    poster_path,
    tagline,
    title,
    video,
    belongs_to_collection__id,
    belongs_to_collection__name,
    belongs_to_collection__poster_path,
    belongs_to_collection__backdrop_path,
    adult,
    backdrop_path,
    case when rn = 1 then 1 else 0 end as is_current,
    dbt_valid_from::DATE as valid_from,
    case when rn = 1 then '9999-12-31'::DATE else(dbt_valid_to::DATE - interval 1 day)::DATE end as valid_to
from last_movies