{{ config(materialized='view') }}

select 
    id as tmdb_id,
    imdb_id,
    status,
    original_title,
    release_date,
    budget,
    revenue,
    runtime,
    popularity,
    vote_average,
    vote_count,
    original_language,
    genres,
    production_companies,
    production_countries,
    spoken_languages,
    origin_country,
    credits,
    overview,
    poster_path,
    tagline,
    title,
    video,
    belongs_to_collection__id,
    belongs_to_collection__name,
    belongs_to_collection__poster_path,
    belongs_to_collection__backdrop_path,
    adult,
    backdrop_path,
    _dlt_load_id as load_id,
    to_timestamp(_dlt_load_id::DOUBLE) AT TIME ZONE 'America/Argentina/Buenos_Aires' as load_date,
    _dlt_id as dlt_id 
from {{source('shared_movies', 'tmdb_movies')}}